In [18]:
import numpy as np
#1(2)
a= np.array([[2, 3, 1], [-1, 1, 0], [1, 2, -1]])
b= np.array([[1, 2, 1], [0, 1, 2], [3, 1, 1]])
ab = np.dot(a, b)
ba = np.dot(b, a)
c = ab - ba
print(c)



[[ 4  1  9]
 [-2 -6  3]
 [-8 -9  2]]


In [35]:
#2(1)
a=np.array([[-1, 2], [0, 1]])
a2 = np.dot(a, a)
print(a2)


[[1 0]
 [0 1]]


In [19]:
#3(3)
a= np.array([[3, 0, 7], [-4, 2, 3], [-1, 1, 2]])
b= np.array([[1], [2], [4]])
ab = np.dot(a, b)
print(ab)

[[31]
 [12]
 [ 9]]


In [11]:
#4(1)
a= np.array([[2, 3, 4], [1, 0, 6], [7, 8, 9]])
a_det = np.linalg.det(a)
print(format(a_det, '.9g'))


35


In [13]:
#5(2)
a= np.array([[2, 3, 4,1], [1, 2, 3,4], [3, 4, 1,2],[4, 1, 2,3]])
a_det = np.linalg.det(a)
print(format(a_det, '.9g'))

-160


In [17]:
#6(1)
a= np.array([[1, 2, -3], [0, 1, 2], [0,0,1]])
a_ob = np.linalg.inv(a)
print(a_ob)


[[ 1. -2.  7.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]]


In [44]:
#7(1)
a = np.array([[1, 2, 3, 4],[3, -1, 2, 5], [1, 2, 3, 4], [1, 3, 4, 5]])
rank = np.linalg.matrix_rank(a)
print(rank)


2


In [33]:
#8(8)
a = np.array([[1, 2, -1],[3, 4, 1],[5, 1, -3]])
b = np.array([-3, 1, -2])
a_inv = np.linalg.inv(a)
xyz = np.dot(a_inv, b)
print(xyz)
print("x=",xyz[0],"y=",xyz[1],"z=",xyz[2])
result = np.linalg.solve(a, b).round(3)
print("Результат за допомогою solve():")
print(result)

[ 1. -1.  2.]
x= 1.0 y= -1.0 z= 2.0
Результат за допомогою solve():
[ 1. -1.  2.]


In [42]:
#2(5)
import random
n = 5
m = 5
a = np.random.randint(0, 100, size=(n, m))
print(a)
total_sum = np.sum(a)
print("Сума всіх елементів матриці:", total_sum)
row_sums = np.sum(a, axis=1)
print("Суми елементів кожного рядка:")
for i in range(len(row_sums)):
    print(i+1," ",row_sums[i])
dolyasum = row_sums / total_sum
print("Долі сум кожного рядка в загальній сумі:")
for i in range(len(dolyasum)):
    print(i+1," ",dolyasum[i])


[[44 89 81 82 70]
 [11 82 19 89 51]
 [11 91  8 71 41]
 [70 18 23 54 30]
 [71 63 53 44 95]]
Сума всіх елементів матриці: 1361
Суми елементів кожного рядка:
1   366
2   252
3   222
4   195
5   326
Долі сум кожного рядка в загальній сумі:
1   0.2689199118295371
2   0.18515797207935342
3   0.16311535635562086
4   0.14327700220426157
5   0.23952975753122704
